export const MESSAGE ={
    ROUTER_POST_INFO:'EmpRouter post(): post Method called.',
    ROUTER_GETALL_INFO:'EmpRouter get():get method called to get all data in the table.',
    ROUTER_GET_INFO:'EmpRouter get(): get Method called for getBYId.',
    ROUTER_UPDATE_INFO:'EmpRouter put():put method is called for update the table.',
    ROUTER_DELETE_INFO:'EmpRouter delete():Delete method was called for deletion .',
    CONTROLLER_POST_INFO:'EmpController empCreate():Table creation in Post Method.',
    CONTROLLER_GETALL_INFO:'EmpController empGet():Table getting by getAll Method.',
    CONTROLLER_GET_INFO:'EmpController empRead():Table getting by Id in getBYId Method.',
    CONTROLLER_UPDATE_INFO:'EmpController empUpdate():Table updates by update Method.',
    CONTROLLER_DELETE_INFO:'EmpController empDelete():Table deleted by delete Method.',
    CONTROLLER_POST_ERROR:'EmpController empCreate():Error on creating the table in Post Method.===>',
    CONTROLLER_GETALL_ERROR:'EmpController empGetAll():Error on getting all data in the table by getAll Method.===>',
    CONTROLLER_GET_ERROR:'EmpController empRead():Error on getting the data by id in the table by getBYId Method.===>',
    CONTROLLER_UPDATE_ERROR:'EmpController empUpdate():Error on updating the table by id using put Method.===>',
    CONTROLLER_DELETE_ERROR:'EmpController empDeleted():Error on deleting in the table by id using delete Method.===>',
    SERVICE_POST_INFO:'EmpService empCreate():Table creation in Post Method.',
    SERVICE_GETALL_INFO:'EmpService empGet():Table getting by getAll Method.',
    SERVICE_GET_INFO:'EmpService empRead():Table getting data by id in getBYId Method.',
    SERVICE_UPDATE_INFO:'EmpService empUpdate():Table updation by update Method.',
    SERVICE_DELETE_INFO:'EmpService empDelete():Table deletion by delete Method.',
    DAO_POST_INFO:'EmpDao save():Saving the data through Post Method.',
    DAO_GETALL_INFO:'EmpDao getAll():Getting the data from table by getAll Method.',
    DAO_GET_INFO:'EmpDao getById():Getting the data by id in from table using getBYId Method.',
    DAO_UPDATE_INFO:'EmpDao findByIdAndUpdate():Table updatation by update Method.',
    DAO_DELETE_INFO:'EmpDao findByIdAndDelete():Table deletion by delete Method.'
}
